- LABEL: "CAM1"
  CAMERA_TYPE: "IP"
  CAMERA_IP: "192.168.0.201"
  CAMERA_LOGIN: "admin"
  CAMERA_PASSWORD: "admin"
  NUMFRAMES: 9
- LABEL: "CAM2"
  CAMERA_TYPE: "IP"
  CAMERA_IP: "192.168.0.202"
  CAMERA_LOGIN: "admin"
  CAMERA_PASSWORD: "admin"
  NUMFRAMES: 9
- LABEL: "CAM3"
  CAMERA_TYPE: "IP"
  CAMERA_IP: "192.168.0.203"
  CAMERA_LOGIN: "admin"
  CAMERA_PASSWORD: "admin"
  NUMFRAMES: 6
- LABEL: "CAM4"
  CAMERA_TYPE: "IP"
  CAMERA_IP: "192.168.0.204"
  CAMERA_LOGIN: "admin"
  CAMERA_PASSWORD: "admin"
  NUMFRAMES: 7
- LABEL: "CAM5"
  CAMERA_TYPE: "IP"
  CAMERA_IP: "192.168.0.205"
  CAMERA_LOGIN: "admin"
  CAMERA_PASSWORD: "admin"
  NUMFRAMES: 9
- LABEL: "CAM6"
  CAMERA_TYPE: "IP"
  CAMERA_IP: "192.168.0.206"
  CAMERA_LOGIN: "admin"
  CAMERA_PASSWORD: "admin"
  NUMFRAMES: 4
- LABEL: "CAM7"
  CAMERA_TYPE: "IP"
  CAMERA_IP: "192.168.0.207"
  CAMERA_LOGIN: "admin"
  CAMERA_PASSWORD: "admin"
  NUMFRAMES: 6
- LABEL: "CAM8"
  CAMERA_TYPE: "IP"
  CAMERA_IP: "192.168.0.208"
  CAMERA_LOGIN: "admin"
  CAMERA_PASSWORD: "admin"
  NUMFRAMES: 4
- LABEL: "USB0"
  CAMERA_TYPE: "USB"
  PORTNUM: 0
