CAMERAS:
  - LABEL: "CAM1"
    CAMERA_TYPE: "IP"
    CAMERA_IP: "192.168.1.4"
    CAMERA_LOGIN: "admin"
    CAMERA_PASSWORD: "123456"
    NUMFRAMES: 239
SERVER_HOST: "https://host:port/api/v2/{}"
SERVER_LOGIN: "user@host"
SERVER_PASSWORD: "passwd"
DB_FILE: "localdata.db"
DATADIR: "picts"
LOWLIGHT: 10
EXCLUDE_POS: "65-99,222"