CAMERAS:
  - LABEL: "CAM1"
    CAMERA_TYPE: "IP"
    CAMERA_IP: "192.168.1.4"
    CAMERA_LOGIN: "admin"
    CAMERA_PASSWORD: "123456"
    NUMFRAMES: 239
#239
#  - LABEL: "CAM2"
#    CAMERA_TYPE: "IP"
#    CAMERA_IP: "192.168.1.22"
#    CAMERA_LOGIN: "admin"
#    CAMERA_PASSWORD: "PlantData132"
#    NUMFRAMES: 28
#  - LABEL: "CAM3"
#    CAMERA_TYPE: "IP"
#    CAMERA_IP: "192.168.1.23"
#    CAMERA_LOGIN: "admin"
#    CAMERA_PASSWORD: "PlantData132"
#    NUMFRAMES: 17
#  - LABEL: "CAM4"
#    CAMERA_TYPE: "IP"
#    CAMERA_IP: "192.168.1.24"
#    CAMERA_LOGIN: "admin"
#    CAMERA_PASSWORD: "PlantData132"
#    NUMFRAMES: 9
#  - LABEL: "CAM5"
#    CAMERA_TYPE: "IP"
#    CAMERA_IP: "192.168.1.25"
#    CAMERA_LOGIN: "admin"
#    CAMERA_PASSWORD: "PlantData132"
#    NUMFRAMES: 29
SERVER_HOST: "https://dev.plantdata.fermata.tech:5598/api/v2/{}"
SERVER_LOGIN: "loratest@fermata.tech"
SERVER_PASSWORD: "Ji9aix8r"
DB_FILE: "localdata.db"
DATADIR: "picts"
LOWLIGHT: 10
EXCLUDE_POS: "65-99,222"