before_script:
- docker info

stages:
  - test
  - build

test:
  stage: test
  script:
    - echo "Testing............"
    - python3 --version
    - echo $CI_PROJECT_DIR
    #- pip3 install flake8
    #- python -m py_compile api/api.py
    #- flake8 --exit-zero api/api.py

build:
  stage: build
  script:
    - echo "Deploy....."
    - echo "Starting docker....."
    - docker-compose stop api
    - docker-compose up -d --build api
    - echo $CI_BUILDs_DIR/$CI_CONCURRENT_ID/$CI_PROJECT_NAMESPACE/$CI_PROJECT_ID
