stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "this is building..."
    - hostname
    - mkdir builds
    - touch builds/data.txt
    - echo "ololo" > builds/data.txt
    - ls -latr
  artifacts:
    paths:
      - builds/

test:
  stage: test
  script:
    - echo "this is testing"
    - hostname
    - test -f builds/data.txt
    - ls -latr
    #- grep "true" builds/data.txt

