stages:
  - test
  - build

test:
  stage: test
  script:
    - echo "Testing..."
    - python --version
    - pip3 install flake8
    - python -m py_compile api/api.py
    - flake8 --exit-zero api/api.py

build:
  stage: build
  script:
    - echo "Deploy..."
    - echo "Starting docker"
    - docker-compose up --build api

