before_script:
- docker info

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - echo "Testing............"
    - python3 --version
    - echo $CI_PROJECT_DIR

deploy_live:
  stage: deploy
  script:
    - echo "Deploy....."
    - echo "Starting docker....."
    - docker-compose stop api redis celery celery-beat
    - docker-compose up -d --build redis celery celery-beat api 
    - echo $CI_BUILDs_DIR/$CI_CONCURRENT_ID/$CI_PROJECT_NAMESPACE/$CI_PROJECT_ID
  environment:
    name: live
  variables:
    PICT_DIR: $ENV_PICT_DIR_LIVE
    APP_PORT: $CI_LIVE_PORT
  only:
    - master    
