stages:
  - build
  - test

test:
  stage: build
  script:
    - echo "this is building..."
    - hostname
    - pip3 install flake8
    - flake8 api/api.py
  #artifacts:
  #  paths:
  #    - builds/

build:
  stage: test
  script:
    - echo "this is testing"
    - hostname
    - test -f builds/data.txt
    - ls -latr
    #- grep "true" builds/data.txt

