image: docker:latest

variables:
  DOCKER_DRIVER: overlay
  
services:
- docker:dind

before_script:
- docker info
- apk update
- apk upgrade
- apk add python python-dev py-pip build-base
- pip install docker-compose

stages:
  - test
  - build

test:
  stage: test
  script:
    - echo "Testing...."
    - python3 --version
    - pip3 install flake8
    - python -m py_compile api/api.py
    - flake8 --exit-zero api/api.py

build:
  stage: build
  script:
    - echo "Deploy...."
    - echo "Starting docker..."
    - docker-compose up --build api

