version: '3'

services:
  
  api_dev:
    build: ./api
    volumes:
      - ./api:/app
      - ./.data/pip-cache:/root/.cache/pip
      - ./.data/fonts:/data/fonts
      - ./.socket:/socket
      - $PICT_DIR:/data/picts
      - /etc/localtime:/etc/localtime
      - /var/run/mysqld/mysqld.sock:/etc/mysql.sock
    environment:
      APPSETTINGS: config_docker.py
      TEXT_FONT: /data/fonts/truetype/liberation/LiberationSans-Regular.ttf
      HOST_ADDR: $ENV_HOST_ADDR
      DBUSER: $DBUSER
      DBPASS: $DBPASS
      DBNAME: $DBNAME
      MAILUSER: $MAILUSER
      MAILPASS: $MAILPASS
      REDIS_HOST: redis_dev
      REDIS_PORT: 6379
      REDIS_DB: 0
    depends_on:
      - redis_dev
    ports:
      - "$APP_PORT:8000"


  redis_dev:
    image: redis:alpine


  celery_dev:
    build: ./api
    command: celery worker -E -A api.celery --loglevel=info --logfile celery.worker.log
    volumes:
      - ./api:/app
      - ./.data/fonts:/data/fonts
      - /etc/localtime:/etc/localtime
      - $PICT_DIR:/data/picts
      - /var/run/mysqld/mysqld.sock:/tmp/mysql.sock
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      APPSETTINGS: config_docker.py
      TEXT_FONT: /data/fonts/truetype/liberation/LiberationSans-Regular.ttf
      HOST_ADDR: $ENV_HOST_ADDR
      DBUSER: $DBUSER
      DBPASS: $DBPASS
      DBNAME: $DBNAME
      MAILUSER: $MAILUSER
      MAILPASS: $MAILPASS
      REDIS_HOST: redis_dev
      REDIS_PORT: 6379
      REDIS_DB: 1
    depends_on:
      - redis_dev


  celery-beat_dev:
    build: ./api
    command: celery beat -A api.celery --logfile celery.beat.log
    volumes:
      - ./api:/app
      - ./.data/fonts:/data/fonts
      - /etc/localtime:/etc/localtime
      - $PICT_DIR:/data/picts
      - /var/run/mysqld/mysqld.sock:/tmp/mysql.sock
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      APPSETTINGS: config_docker.py
      TEXT_FONT: /data/fonts/truetype/liberation/LiberationSans-Regular.ttf
      HOST_ADDR: $ENV_HOST_ADDR
      DBUSER: $DBUSER
      DBPASS: $DBPASS
      DBNAME: $DBNAME
      MAILUSER: $MAILUSER
      MAILPASS: $MAILPASS
      REDIS_HOST: redis_dev
      REDIS_PORT: 6379
      REDIS_DB: 1
    depends_on:
      - redis_dev  
