version: '3'

services:
  
  api:
    build: ./api
    volumes:
      - ./api:/app
      - ./.data/pip-cache:/root/.cache/pip
      - ./.data/fonts:/data/fonts
      - ./.socket:/socket
      - $CI_PICT_DIR:/data/picts
    environment:
      APPSETTINGS: config_docker.py
      TEXT_FONT: /data/fonts/truetype/liberation/LiberationSans-Regular.ttf
    ports:
      - "$CI_LIVE_PORT:8000"
      - 6379:6379
  #database:
  #  image: mysql:5.7
  #  #volumes:
  #  #  - ./.data/database:/var/lib/mysql
  #  environment:
  #    MYSQL_ROOT_PASSWORD: root
  #    MYSQL_DATABASE: root
