"""Image Label Str to Text

Revision ID: 01c69bb1022b
Revises: 1fd5caea7aa2
Create Date: 2019-10-31 13:07:38.348034

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '01c69bb1022b'
down_revision = '1fd5caea7aa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_picture', 'label')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_picture', sa.Column('label', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
