"""empty message

Revision ID: 04cd023e709b
Revises: f50f2fbf4e19
Create Date: 2020-01-31 04:37:30.234415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04cd023e709b'
down_revision = 'f50f2fbf4e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('probe_data', sa.Column('value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('probe_data', 'value')
    # ### end Alembic commands ###
