"""added wght0 field

Revision ID: 112de430b9f9
Revises: 
Create Date: 2019-09-12 12:29:01.990772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112de430b9f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('wght0', sa.Numeric(precision=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data', 'wght0')
    # ### end Alembic commands ###
