"""empty message

Revision ID: 1a70e1184501
Revises: 04cd023e709b
Create Date: 2020-01-31 10:57:35.906653

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a70e1184501'
down_revision = '04cd023e709b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_probes',
    sa.Column('data_id', sa.Integer(), nullable=True),
    sa.Column('probe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['data_id'], ['data.id'], ),
    sa.ForeignKeyConstraint(['probe_id'], ['probe.id'], )
    )
    op.drop_constraint('probe_ibfk_3', 'probe', type_='foreignkey')
    op.drop_column('probe', 'data_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('probe', sa.Column('data_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('probe_ibfk_3', 'probe', 'data', ['data_id'], ['id'])
    op.drop_table('data_probes')
    # ### end Alembic commands ###
