"""Image Original

Revision ID: 1fd5caea7aa2
Revises: e24f30f7c377
Create Date: 2019-10-27 01:10:03.677525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fd5caea7aa2'
down_revision = 'e24f30f7c377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_picture', sa.Column('original', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_picture', 'original')
    # ### end Alembic commands ###
