"""Image Label Str to Text

Revision ID: 2f0974a562a5
Revises: 01c69bb1022b
Create Date: 2019-10-31 13:07:49.012220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f0974a562a5'
down_revision = '01c69bb1022b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_picture', sa.Column('label', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_picture', 'label')
    # ### end Alembic commands ###
