"""added more weight fields

Revision ID: 7b665515259b
Revises: c78d280f714d
Create Date: 2019-10-10 14:56:33.975720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b665515259b'
down_revision = 'c78d280f714d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('wght1', sa.Numeric(precision=3), nullable=True))
    op.add_column('data', sa.Column('wght2', sa.Numeric(precision=3), nullable=True))
    op.add_column('data', sa.Column('wght3', sa.Numeric(precision=3), nullable=True))
    op.add_column('data', sa.Column('wght4', sa.Numeric(precision=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data', 'wght4')
    op.drop_column('data', 'wght3')
    op.drop_column('data', 'wght2')
    op.drop_column('data', 'wght1')
    # ### end Alembic commands ###
