"""empty message

Revision ID: 95218472d3f9
Revises: 6a0bbf22ebd7
Create Date: 2020-01-31 02:43:51.874295

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '95218472d3f9'
down_revision = '6a0bbf22ebd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data', 'wght2')
    op.drop_column('data', 'soilmoist')
    op.drop_column('data', 'lux')
    op.drop_column('data', 'hum0')
    op.drop_column('data', 'temp1')
    op.drop_column('data', 'wght0')
    op.drop_column('data', 'tempA')
    op.drop_column('data', 'wght3')
    op.drop_column('data', 'wght1')
    op.drop_column('data', 'temp0')
    op.drop_column('data', 'wght4')
    op.drop_column('data', 'hum1')
    op.drop_column('data', 'co2')
    op.drop_column('data', 'uv')
    op.add_column('probe', sa.Column('sensor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'probe', 'sensor', ['sensor_id'], ['id'])
    op.drop_column('probe', 'label')
    op.drop_column('probe', 'maxvalue')
    op.drop_column('probe', 'minvalue')
    op.drop_column('probe', 'ptype')
    op.add_column('probe_data', sa.Column('label', sa.String(length=200), nullable=True))
    op.add_column('probe_data', sa.Column('ptype', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('probe_data', 'ptype')
    op.drop_column('probe_data', 'label')
    op.add_column('probe', sa.Column('ptype', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('probe', sa.Column('minvalue', mysql.DECIMAL(precision=3, scale=0), nullable=True))
    op.add_column('probe', sa.Column('maxvalue', mysql.DECIMAL(precision=3, scale=0), nullable=True))
    op.add_column('probe', sa.Column('label', mysql.VARCHAR(length=200), nullable=True))
    op.drop_constraint(None, 'probe', type_='foreignkey')
    op.drop_column('probe', 'sensor_id')
    op.add_column('data', sa.Column('uv', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('data', sa.Column('co2', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('data', sa.Column('hum1', mysql.DECIMAL(precision=3, scale=0), nullable=True))
    op.add_column('data', sa.Column('wght4', mysql.DECIMAL(precision=3, scale=0), nullable=True))
    op.add_column('data', sa.Column('temp0', mysql.DECIMAL(precision=3, scale=0), nullable=True))
    op.add_column('data', sa.Column('wght1', mysql.DECIMAL(precision=3, scale=0), nullable=True))
    op.add_column('data', sa.Column('wght3', mysql.DECIMAL(precision=3, scale=0), nullable=True))
    op.add_column('data', sa.Column('tempA', mysql.DECIMAL(precision=3, scale=0), nullable=True))
    op.add_column('data', sa.Column('wght0', mysql.DECIMAL(precision=3, scale=0), nullable=True))
    op.add_column('data', sa.Column('temp1', mysql.DECIMAL(precision=3, scale=0), nullable=True))
    op.add_column('data', sa.Column('hum0', mysql.DECIMAL(precision=3, scale=0), nullable=True))
    op.add_column('data', sa.Column('lux', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('data', sa.Column('soilmoist', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('data', sa.Column('wght2', mysql.DECIMAL(precision=3, scale=0), nullable=True))
    # ### end Alembic commands ###
