"""empty message

Revision ID: a01c436142a0
Revises: 95218472d3f9
Create Date: 2020-01-31 02:46:46.672506

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a01c436142a0'
down_revision = '95218472d3f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('probe_ibfk_1', 'probe', type_='foreignkey')
    op.drop_column('probe', 'data_id')
    op.add_column('probe_data', sa.Column('data_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'probe_data', 'data', ['data_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'probe_data', type_='foreignkey')
    op.drop_column('probe_data', 'data_id')
    op.add_column('probe', sa.Column('data_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('probe_ibfk_1', 'probe', 'data', ['data_id'], ['id'])
    # ### end Alembic commands ###
