"""Removed zone fields

Revision ID: aa5ca6485b56
Revises: 7f034d49c58b
Create Date: 2019-12-28 15:44:19.239240

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa5ca6485b56'
down_revision = '7f034d49c58b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('picture_zone', 'original')
    op.drop_column('picture_zone', 'label')
    op.drop_column('picture_zone', 'thumbnail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picture_zone', sa.Column('thumbnail', mysql.TEXT(), nullable=True))
    op.add_column('picture_zone', sa.Column('label', mysql.TEXT(), nullable=True))
    op.add_column('picture_zone', sa.Column('original', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
