"""camera image labels

Revision ID: c78d280f714d
Revises: 112de430b9f9
Create Date: 2019-09-21 01:01:06.021002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c78d280f714d'
down_revision = '112de430b9f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_picture', sa.Column('label', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_picture', 'label')
    # ### end Alembic commands ###
