"""Image Thumbnail

Revision ID: e24f30f7c377
Revises: 7b665515259b
Create Date: 2019-10-23 17:40:07.043505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e24f30f7c377'
down_revision = '7b665515259b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_picture', sa.Column('thumbnail', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_picture', 'thumbnail')
    # ### end Alembic commands ###
