"""empty message

Revision ID: f28c7cd8bf98
Revises: 1a70e1184501
Create Date: 2020-01-31 11:45:51.771005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f28c7cd8bf98'
down_revision = '1a70e1184501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('minvalue', sa.Float(), nullable=True),
    sa.Column('maxvalue', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('probes_types',
    sa.Column('sensor_type_id', sa.Integer(), nullable=True),
    sa.Column('probe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['probe_id'], ['probe.id'], ),
    sa.ForeignKeyConstraint(['sensor_type_id'], ['sensor_type.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('probes_types')
    op.drop_table('sensor_type')
    # ### end Alembic commands ###
