DEBUG = True
DEVELOPMENT = True
SECRET_KEY='secretkeyformyapp'
SQLALCHEMY_DATABASE_URI='mysql+pymysql://user:password@host/database_name'
SQLALCHEMY_TRACK_MODIFICATIONS = False
FILE_PATH = "/path/to/directory/woere/to/store/pictures"
CF_LOGIN = "user"
CF_PASSWORD = "pass"
CF_HOST = "https://host/{}"
CLASSIFY_ZONES = True
FONT = "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf"
FONTSIZE = 50
TEMPDIR = "/path/to/temporary/dir"
REDIS_HOST = "localhost"
REDIS_PORT = 6379
REDIS_DB = 3
CACHE_DB = 4
API_VERSION = 2
SEND_EMAILS = True
