DEBUG = True
DEVELOPMENT = True
SECRET_KEY='secretkeyformyapp'
SQLALCHEMY_DATABASE_URI='mysql+pymysql://plantdata:plantdatapass@192.168.1.4/plantdb'
SQLALCHEMY_TRACK_MODIFICATIONS = False
FILE_PATH = "/media/MEDIA/PLANTDATA"
CF_LOGIN = "demouser@host"
CF_PASSWORD = "demopass"
CF_HOST = "https://host:port/api/v1/{}"
CLASSIFY_ZONES = True
FONT = "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf"
FONTSIZE = 50
TEMPDIR = "/media/MEDIA/TMP"
