Bottom Black Camera 1:
 - label: zone 1
   left: 150
   top: 600
   right: 550
   bottom: 1000
 - label: zone 2
   left: 600
   top: 200
   right: 1000
   bottom: 600
 - label: zone 3
   left: 1000
   top: 100
   right: 1400
   bottom: 500
Bottom Black Camera 3:
 - label: zone 1
   left: 700
   top: 150
   right: 1200
   bottom: 650
 - label: zone 2
   left: 1400
   top: 600
   right: 2000
   bottom: 1000
Top White Camera 1:
 - label: zone 1
   left: 900
   top: 780
   right: 1200
   bottom: 1080
 - label: zone 2
   left: 1200
   top: 100
   right: 1500
   bottom: 400
